<section>
    <h2>Acerca del proyecto</h2>
    <p>
        Este proyecto tiene como objetivo mostrar el catalogo de películas de un videoclub aplicando
        los conceptos aprendidos en la materia de web 2 de la tecnicatura en desarrollo de aplicaciones 
        informáticas (TUDAI). 
    </p>
    <p>
        Para el desarrollo se utilizó el enfoque Server Side Rendering, 
        con el lenguaje de programación PHP para el backend, mysql para la base de datos y hojas de estilos 
        hechas a mano. 
    </p>
    <h3>Desarrolladores</h3>
    <h4>Luciano Sánchez Tomé</h4>
    <h4>Julieta Watts</h4>
</section>
