<section class="about">
    <h2 >Acerca del proyecto</h2>
    <p>
        Este proyecto tiene como objetivo mostrar el catálogo de películas de un videoclub aplicando
        los conceptos aprendidos en la materia de web 2 de la tecnicatura en desarrollo de aplicaciones 
        informáticas (TUDAI). 
    </p>
    <p>
        Para el desarrollo se utilizó el enfoque Server Side Rendering, 
        con el lenguaje de programación PHP para el backend, MySQL para la base de datos y hojas de estilos CSS 
        hechas a mano. 
    </p>
    <p> El sitio ofrece una interfaz de administrador y una interfaz pública. Desde la interfaz pública se 
        permiten las operaciones de filtrado de películas por director, ver el detalle de las películas y visualizar
        el catálogo de películas y directores del videoclub. Desde la interfaz de administrador, se permite 
        gestionar el catálogo de películas y directores, subiendo, editando y eliminando contenido de los mismos. 
        Para iniciar como administrador es necesario iniciar sesión con el usuario y contraseña correspondiente. 
    </p>
    <h3 class="resaltado"> Posibles ampliaciones futuras del proyecto: </h3>
    <ul>
        <li>Poder filtrar por más atributos las películas</li>
        <li>Crear un paginado del listado de películas y directores</li>
        <li>Tener un carrito de alquiler/compra de las películas como usuario</li>
        <li>Poder gestionar las reservas desde el lado del administrador</li>
    </ul>
    <h3 class="resaltado">Desarrolladores</h3>
    <ul>
        <li class="descripcion">Luciano Sánchez Tomé</li>
        <li class="descripcion">Julieta Watts</li>
    </ul>

</section>
