<section class="admin-page">
    <h2>Listado de Películas</h2>

    <table class="admin-table">
        <thead>
            <tr>
                <th>Título</th>
                <th>Duración</th>
                <th>Fecha de Lanzamiento</th>
                <th>ATP</th>
                <th>Director</th>
                <th>Distribuidora</th>
                <th>Género</th>
                <th>Precio</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($movies as $movie): ?>
                <tr>
                    <td><?= $movie->titulo ?></td>
                    <td><?= $movie->duracion ?></td>
                    <td><?= $movie->fecha_lanzamiento ?></td>
                    <td><?= $movie->atp ?></td>
                    <td><?= $movie->nombre_director ?></td>
                    <td><?= $movie->distribuidora ?></td>
                    <td><?= $movie->genero ?></td>
                    <td>$ <?= $movie->precio ?></td>
                    <td><a class="button" href="<?= BASE_URL ?>admin/edit/<?= $movie->id ?>">Editar</a></td>
                    <td><a class="button" href="<?= BASE_URL ?>admin/delete/<?= $movie->id ?>">Eliminar</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <a class="button" href="<?= BASE_URL ?>admin/add">Agregar Película</a>
</section>
