
<section class="peliculas-listado">
    <?php foreach ($directors as $director): ?>
        <article class="pelicula-card">
            <h4><?= $director->nombre ?></h4>

            <img src="<?= $director->imagen ?>" 
                 alt="Imagen de <?= $director->nombre ?>">

            <p><?= $director->sexo ?></p>
            <p><?= $director->reputacion ?></p>
            <p><?= $director->fecha_nacimiento ?></p>
            <p><?= $director->pais_origen ?></p>
        </article>
    <?php endforeach; ?>
</section>
