<section class="admin-page">
    <h2>Lista de Directores</h2>
    <table class="admin-table">
        <thead>
            <th>Nombre</th>
            <th>Sexo</th>
            <th>Fecha nacimiento</th>
            <th>Reputacion</th>
            <th>Pais origen</th>
            <th>Imagen</th>
            <th>Acciones</th>
        </thead>
        <tbody>
            <?php foreach ($directors as $director): ?> 
                <tr>
                    <td><?= $director->nombre ?></td>
                    <td><?= $director->sexo ?></td>
                    <td><?= $director->fecha_nacimiento ?></td>
                    <td><?= $director->reputacion ?></td>
                    <td><?= $director->pais_origen ?> </td>
                    <td><a href="<?= $director->imagen ?>" target="_blank">Ver imagen</a></td>
                    <td>
                        <section class="button-container">
                            <a class="button" href="edit_director/<?= $director->id?>">Editar</a>
                            <a class="button" href="delete_director/<?= $director->id?>">Eliminar</a>
                        </section>
                        
                    </td>
                </tr>
            <?php  endforeach; ?>
        </tbody>
    </table>
    <section class="button-container">
        <a class="button" href="<?= BASE_URL ?>admin">Volver</a>
        <a class="button" href="add_director">Agregar</a>
    </section>

</section>
