
<section class="listado">
    <?php foreach ($directors as $director): ?>
        <article class="card">
            <h4><?= $director->nombre ?></h4>

            <img src="<?= $director->imagen ?>" 
                 alt="Imagen de <?= $director->nombre ?>">
            <p class="resaltado">Reputación: <?= $director->reputacion ?> estrellas</p>
            <p class="descripcion">Género: <?= $director->sexo ?></p>
            <p class="descripcion">Fecha de nacimiento:  <?= $director->fecha_nacimiento ?></p>
            <p class="descripcion">País de origen: <?= $director->pais_origen ?></p>
        </article>
    <?php endforeach; ?>
</section>
