<?php
require_once "./controllers/auth_controller.php";
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Películas</title>
    <link rel="stylesheet" href="<?= BASE_URL ?>css/styles.css">
</head>
<body>
    <header class="main-header">
        <h1><a href="<?= BASE_URL ?>peliculas">Catálogo de Películas</a></h1>
        <nav>
            <ul>
                <li><a href="<?= BASE_URL ?>peliculas">Peliculas</a></li>
                <li><a href="<?= BASE_URL ?>directores">Directores</a></li>
                <li><a href="<?= BASE_URL ?>about">Acerca de</a></li>
                <?php if (empty($request->usuario->nombre)): ?>
                    <li><a href="<?= BASE_URL ?>admin">Panel Admin</a></li>
                <?php endif; ?>
                <?php if (!empty($request->usuario->nombre)): ?>
                    <li><a href="<?= BASE_URL ?>login">Login</a></li>
                    <?php else: ?>           
                        <li><a href="<?= BASE_URL ?>logout">Cerrar Sesion</a></li>
                <?php endif; ?>
            </ul>
        </nav>
    </header>
    <main>
