<section class="pelicula-detalle">
    <img src="<?= htmlspecialchars($movie->imagen) ?>" alt="Imagen de <?= htmlspecialchars($movie->titulo) ?>">

    <div class="pelicula-detalle-info">
        <h2><?= htmlspecialchars($movie->titulo) ?></h2>
        <p><?= htmlspecialchars($movie->descripcion) ?></p>
        <p class="precio">Precio: $<?= htmlspecialchars($movie->precio) ?></p>
        <p class="director">Director: <?= htmlspecialchars($movie->nombre_director) ?></p>
        <p class="categoria">Género: <?= htmlspecialchars($movie->genero) ?></p>
        <a href="<?= BASE_URL ?>peliculas">Volver</a>
    </div>
</section>
