
<section>
    <form action="peliculas">
        <label>Filtrar por director</label>
        <select name="director_id" class="input" required>
            <?php foreach ($directors as $d): ?>
                <option value="<?= $d->id ?>">
                    <?= $d->nombre ?>
                </option>
            <?php endforeach; ?>
        </select>
        <button type="submit">Filtrar</button>
    </form>
</section>
<section class="peliculas-listado">
    <?php foreach ($movies as $movie): ?>
        <article class="pelicula-card">
            <h4><?= $movie->titulo ?></h4>

            <img src="<?= $movie->imagen ?>" 
                 alt="Imagen de <?= $movie->titulo ?>">

            <p><?= $movie->descripcion ?></p>

            <p class="precio">Precio: $<?= $movie->precio ?></p>
            <p class="director">Director: <?= $movie->nombre_director ?></p>
            <p class="categoria">Género: <?= $movie->genero ?></p>

            <a href="<?= BASE_URL ?>peliculas/<?= $movie->id ?>">Ver más</a>
        </article>
    <?php endforeach; ?>
</section>
