<section class="admin-page">
    <?php
        $accion = $movie ? 'edit_movie' : 'add_movie';
        $tituloForm = $movie ? 'Editar Película' : 'Agregar Película';
        $buttonText = $movie ? 'Guardar Cambios' : 'Agregar';


        $Titulo = $movie->titulo ?? '';
        $Duracion = $movie->duracion ?? '';
        $Descripcion = $movie->descripcion ?? '';
        $Precio = $movie->precio ?? '';
        $Imagen = $movie->imagen ?? '';
        $Fecha = $movie->fecha_lanzamiento ?? '';
        $Atp = $movie->atp ?? '';
        $Distribuidora = $movie->distribuidora ?? '';
        $Genero = $movie->genero ?? '';
        $DirectorId = $movie->director_id ?? '';
        $generos = ['Acción', 'Comedia', 'Drama', 'Terror', 'Romance', 'Suspenso'];
    ?>

    <h2><?= $tituloForm ?></h2>

    <?php if ($error): ?>
        <p class="login-error"><?= $error ?></p>
    <?php endif; ?>

    <form method="POST" class="admin-form" action="<?= BASE_URL ?>admin/<?= $accion ?>/<?= $movie->id ?? '' ?>">

        <label>Título</label>
        <input type="text" name="titulo" class="input" value="<?= $Titulo ?>" required>

        <label>Duración</label>
        <input type="number" name="duracion" class="input" value="<?=$Duracion ?>" required>

        <label>Descripción</label>
        <textarea name="descripcion" class="input" required><?= $Descripcion ?></textarea>

        <label>Precio</label>
        <input type="number" name="precio" class="input" value="<?= $Precio ?>" required>

        <label>URL Imagen</label>
        <input type="text" name="imagen" class="input" value="<?= $Imagen ?>" required>

        <label>Fecha de Lanzamiento</label>
        <input type="date" name="fecha" class="input" value="<?= $Fecha ?>" required>

        <label>ATP</label>
        <input type="number" min='0' max='1' name="atp" class="input" value="<?= $Atp ?>" required>

        <label>Distribuidora</label>
        <input type="text" name="distribuidora" class="input" value="<?= $Distribuidora ?>" required>

        <label>Género</label>
        <select name="genero" class="input" required>
            <?php foreach ($generos as $g): ?>
                <option value="<?= $g ?>" <?= ($Genero == $g) ? 'selected' : '' ?>><?= $g ?></option>
            <?php endforeach; ?>
        </select>

        <label>Director</label>
        <select name="director_id" class="input" required>
            <?php foreach ($directors as $d): ?>
                <option value="<?= $d->id ?>" <?= ($DirectorId == $d->id) ? 'selected' : '' ?>>
                    <?= $d->nombre ?>
                </option>
            <?php endforeach; ?>
        </select>

        <button type="submit" class="button"><?= $buttonText ?></button>
    </form>
</section>